# Project: WordCount
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = WordCount/wordCount.o
LINKOBJ  = WordCount/wordCount.o
LIBS     = -L"D:/LenovoSoftstore/Install/DevC/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"D:/LenovoSoftstore/Install/DevC/MinGW64/include" -I"D:/LenovoSoftstore/Install/DevC/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/DevC/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/LenovoSoftstore/Install/DevC/MinGW64/include" -I"D:/LenovoSoftstore/Install/DevC/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/DevC/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/LenovoSoftstore/Install/DevC/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WordCount.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

WordCount/wordCount.o: WordCount/wordCount.c
	$(CC) -c WordCount/wordCount.c -o WordCount/wordCount.o $(CFLAGS)
